# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'DemoSortedJSONCoder' do
  pod 'SortedJSONCoder', :path => '../'
end

target 'DemoSortedJSONCoderSwift' do
   use_frameworks!
   pod 'SortedJSONCoder', :path => '../'
end
